
# @Name
GET http://localhost:3333/schedules

###

# @Agendamento único
GET http://localhost:3333/schedules/f6819a21-2b77-4448-8d5b-875c4fd35b90

###

# @Tutors
GET http://localhost:3333/tutors

###

# @Tutor único
GET http://localhost:3333/tutors/3dba6a25-2133-4928-bed1-1e863094b5f4

###

# @Registrando tutor
POST http://localhost:3333/register
content-type: application/json

{
  "name": "Pedro Lucas",
  "email": "pe.lucs0089@gmail.com",
  "phone": "83987296826",
  "address": "Rua Belarminio Timóteo 113 - Palmeira"
}